server:
  port: 8003
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

spring:
  #config:
    #import: optional:configserver:http://localhost:8888
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: 'http://localhost:9002/'
          predicates:
            - Path=/product/**
        - id: order-service
          uri: 'http://localhost:8002/'
          predicates:
            - Path=/orders/**
        - id: cart-service
          uri: 'http://localhost:8000/'
          predicates:
          - Path=/carts/**
        - id: profile-service
          uri: 'http://localhost:9090/'
          predicates:
            - Path=/user/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"
            allowCredentials: true
